project_name: 'tongue_cls'

device: '0, 1'  # GPU selection
multilabels: True
num_workers: 16  # Workers used for dataloader
model_level: 0  # There are multiple levels of efficientnet, details in https://github.com/lukemelas/EfficientNet-PyTorch 
weights: 'adv-efficientnet-b0.pth'  # Pretrained weights, please download from the repo above
resume: ''
num_classes: 24  # labels outnumbered num_classes-1 will be deprecated
img_size: 604  # [b0, b1, b2, b3, b4, b5, b6, b7, b8] -> [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]

epoch: 100
batch_size: 64  # Must be multiples of the gpus

# learning rate related params
lr: 0.01
optim: 'SGD'  # 'adamw', 'rmsprop', 'SGD'
scheduler: 'auto'  # 'exp', 'cosine', 'auto'
momentum: 0.937

# Overfitting related params
weight_decay: 0.0005
ema_decay: 0.99
dropout_rate: 0.3
dropconnect_rate: 0.2

conf_thresh: 0.75  # confidence threshold used in valiation or test， >conf_thresh is considered positive

beta: (0.9, 0.999)  # betas when use adamw 
eps: 0.001  # betas when use rmsprop

# Directory related params
input_dir: '/data/hys/data/tongue/'  # should be absolute path
save_dir: 'outs/'  # should be relative path
